spring:
  application:
    name: realtime
  web:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080

weather:
  api:
    key: ${WEATHER_API_KEY}
